services:
  - type: web
    name: tabletennisresultmaker
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PORT
        value: 5000